name: search

services:
  #  frontend:
  #    container_name: wretch
  #    build:
  #      context: ./frontend
  #      dockerfile: Dockerfile.web
  #    ports:
  #      - "3000:3000"
  #    depends_on:
  #      - backend

  backend:
    container_name: scum
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
      - ./backend/src/main/resources/config.properties:/app/config.properties
    depends_on:
      - db

  db:
    container_name: mongrel
    image: mongo:8.3
    logging:
      driver: "none"
    ports:
      - "27017:27017"
    volumes:
      - mongrel_data:/data/db

#  redis1:
#    container_name: vermin
#    image:
#    ports:
#      - ""
#    volumes:
#      - ""
#
#  redis2:
#    container_name: rat
#
#  redis3:
#    container_name: maggot

volumes:
  mongrel_data: