name: search

services:
  #  frontend:
  #    container_name: wretch
  #    build:
  #      context: ./frontend
  #      dockerfile: Dockerfile.web
  #    ports:
  #      - "3000:3000"
  #    depends_on:
  #      - backend

  backend:
    container_name: scum
    build:
      context: ./backend
      dockerfile: Dockerfile.server
    init: true
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/main/resources/config.properties:/app/config.properties
      - ./backend/data:/app/data
    depends_on:
      db:
        condition: service_started
      redis1:
        condition: service_healthy

  db:
    container_name: mongrel
    image: mongo:8.3
    logging:
      driver: "none"
    #    command: [
    #      "--wiredTigerCollectionBlockCompressor", "zstd",
    #      "--wiredTigerJournalCompressor", "zstd",
    #      "--journalCommitInterval", "500"
    #    ]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  redis1:
    container_name: vermin
    image: redis:8.8-alpine
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli info persistence | grep -q '^loading:0'" ]
      interval: 1m30s
      timeout: 3s
      retries: 5
      start_period: 30s
      start_interval: 1s
    ports:
      - "6379:6379"
    volumes:
      - redis_data1:/data

#  redis2:
#    container_name: rat
#    image: redis:8.8-alpine
#    ports:
#      - "6380:6379"
#    volumes:
#      - redis_data2:/data
#
#  redis3:
#    container_name: maggot
#    image: redis:8.8-alpine
#    ports:
#      - "6381:6379"
#    volumes:
#      - redis_data3:/data

volumes:
  mongo_data:
  mongo_config:
  redis_data1: