FROM maven:3.9-eclipse-temurin-26-alpine AS build
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY . .
RUN mvn package -Dmaven.test.skip=true

FROM eclipse-temurin:26-jre-alpine
WORKDIR /app

COPY --from=build /app/target/Distributed-Search-Engine-1.1-SNAPSHOT.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
#CMD ["java", "-XX:FlightRecorderOptions=stackdepth=128", "-XX:StartFlightRecording=filename=recording.jfr,duration=120s,settings=profile", "-jar", "app.jar"]